import test from "node:test";
import assert from "node:assert/strict";
import { loadKnowledgeBaseV4 } from "./knowledge-base-v4.mjs";
import { generateAIWorkflowV4, InvalidAIGenerationError } from "./ai-generation-v4.mjs";
import { buildLearningExperienceGenerationInput, generateTeacherLearningExperience } from "./ai-learning-experience-ui-service.mjs";
import { resolveAIExecutionPlan } from "./ai-execution-router-v4.mjs";
const classroom={id:"c",age:5,group_context:"Grupo de 5",calendar:{school_year:"2026"}};
const pathway={title:"Explorar",pedagogical_intention:"Investigar juntos",possible_child_actions:"Preguntar y probar"};
function output(workflow){const key=workflow==="project"?"trigger_or_interest":"learning_need_or_context";const paths=workflow==="project"?"possible_pathways":"proposed_situations";return {title:"Propuesta",purpose:"Explorar",[key]:"Interés real",starting_point:"Lo que el grupo observa",primary_competency_ids:[],possible_secondary_competency_ids:[],[paths]:[pathway],spaces_and_materials:["aula"],evidence_opportunities:["explicaciones"],family_or_community_links:[],adjustment_points:["revisar"],flexibility_notes:"Ajustable"}}
test("project y unit usan Sol medium y schemas propios",async()=>{for(const workflow of ["project","unit"]){const plan=resolveAIExecutionPlan({workflow,task:"generation"});assert.equal(plan.model,"gpt-5.6-sol");assert.equal(plan.reasoning_effort,"medium");const requests=[];const result=await generateAIWorkflowV4({workflow,age:5,teacher_request:"x",classroom_context:{group_context:"Grupo"},[workflow==="project"?"project_trigger_or_interest":"learning_need_or_context"]:"Interés real"},{knowledgeBase:await loadKnowledgeBaseV4(),provider:{generate:async request=>{requests.push(request);return output(workflow)}}});assert.equal(requests[0].workflow,workflow);assert.equal(result.validation.schema,`${workflow}-v1`);}});
test("project/unit exigen su contexto y rechazan competencias fuera del bundle",async()=>{assert.throws(()=>buildLearningExperienceGenerationInput({classroom,request:{workflow:"project"}}));assert.throws(()=>buildLearningExperienceGenerationInput({classroom,request:{workflow:"unit"}}));const bad=output("project");bad.primary_competency_ids=["INVENTADA"];const knowledgeBase=await loadKnowledgeBaseV4();await assert.rejects(()=>generateAIWorkflowV4({workflow:"project",age:5,teacher_request:"x",classroom_context:{group_context:"Grupo"},project_trigger_or_interest:"Interés"},{knowledgeBase,provider:{generate:async()=>bad}}),(error)=>error instanceof InvalidAIGenerationError&&error.reason==="project_competency_outside_bundle");});
test("la preparación de proyectos permite esperar la respuesta de Sol",async()=>{let timeout;await generateTeacherLearningExperience({classroom,request:{workflow:"project",project_trigger_or_interest:"Jugar juntos"},createProvider:(_plan,options)=>{timeout=options.timeoutMs;return {};},generate:async()=>({output:output("project"),metadata:{workflow:"project",model:"gpt-5.6-sol"},provenance:{}})});assert.equal(timeout,120_000);});
test("un proyecto integra competencias principales y secundarias incluidas en el contexto curricular",async()=>{const ids=["PS_CONVIVE","COM_ORAL","PS_IDENTIDAD"];const proposal={...output("project"),primary_competency_ids:[ids[0]],possible_secondary_competency_ids:ids.slice(1)};let contextIds=[];const result=await generateAIWorkflowV4({workflow:"project",age:5,teacher_request:"Organizar juegos compartidos",classroom_context:{group_context:"Grupo de prueba"},project_trigger_or_interest:"El grupo organiza sus juegos",competency_ids:ids},{knowledgeBase:await loadKnowledgeBaseV4(),provider:{generate:async(request)=>{contextIds=request.ai_context_bundle.curriculum.competency_cards.map((card)=>card.id);return proposal;}}});assert.deepEqual(contextIds.sort(),[...ids].sort());assert.deepEqual(result.output.possible_secondary_competency_ids,ids.slice(1));});

