import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { validateLearningExperienceProposal } from "./learning-experience-validation.mjs";
const pathway={title:"Camino",pedagogical_intention:"Explorar",possible_child_actions:"Probar"};
function proposal(workflow="project"){return {title:"Título",purpose:"Propósito",starting_point:"Inicio",[workflow==="project"?"trigger_or_interest":"learning_need_or_context"]:"Contexto",primary_competency_ids:["COM_ORAL"],possible_secondary_competency_ids:[],[workflow==="project"?"possible_pathways":"proposed_situations"]:[pathway],spaces_and_materials:["material"],evidence_opportunities:["evidencia"],family_or_community_links:[],adjustment_points:[],flexibility_notes:"Flexible"};}
test("revalida schemas editados y competencias v4",()=>{assert.doesNotThrow(()=>validateLearningExperienceProposal("project",proposal(),new Set(["COM_ORAL"])));assert.doesNotThrow(()=>validateLearningExperienceProposal("unit",proposal("unit"),new Set(["COM_ORAL"])));const bad=proposal();bad.primary_competency_ids=["INVENTADA"];assert.throws(()=>validateLearningExperienceProposal("project",bad,new Set(["COM_ORAL"])));delete bad.purpose;assert.throws(()=>validateLearningExperienceProposal("project",bad,new Set(["COM_ORAL"])));});
test("server cierra ownership, parent, PUT, confirmación y aplicabilidad",async()=>{const source=await readFile(new URL("../../scripts/local-db-server.mjs",import.meta.url),"utf8");for(const pattern of [/method === "PUT"/,/status='draft'/,/validateLearningExperienceProposal\(current\.type/,/pending\.classroom_id/,/pending\.workflow/,/annual_plans where id=\$1 and classroom_id=\$2 and status='active'/,/source\.experience_type !== current\.type/,/castellano_l2_applicable/,/religion_applicable/,/access-control-allow-methods": "GET,POST,PUT,OPTIONS"/])assert.match(source,pattern);assert.doesNotMatch(source,/url\.searchParams\.get\("religion_applicable"/);assert.doesNotMatch(source,/url\.searchParams\.get\("castellano_l2_applicable"/);});
test("editor reabre drafts, separa estados por plan e índice y no usa JSON crudo",async()=>{const source=await readFile(new URL("../features/dashboard/components/learning-experience-generator.tsx",import.meta.url),"utf8");for(const token of ["Abrir borrador","Ver experiencia","annual_plan_id===active?.id","source_proposal_index===index","possible_pathways","proposed_situations","Agregar {type === \"project\" ? \"camino\":\"situación\"}","Competencias primarias","Competencias secundarias","readOnly","editingId"] )assert.match(source,new RegExp(token.replace(/[?]/g,"\\?")));assert.doesNotMatch(source,/JSON\.stringify\(proposal/);});
test("la fase de experiencias no llama OpenAI real",async()=>{const source=await readFile(new URL("../../scripts/local-db-server.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/api\.openai\.com|OPENAI_API_KEY|smoke:openai/i);});
