"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Send, MessageCircle, Users, NotebookPen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiFetch } from "@/src/lib/ayni-api-fetch";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
import { DictationRecorder } from "./dictation-recorder";
import { AyniMascot, JourneySteps } from "./initial-journey-ui";
type Conversation={id:string;revision:number;status:string;messages:{role:string;text:string}[];chips:string[];teacherIdeas:string;calls:number;attempts:number};
export function AnnualPlanningConversation({observations,families,unknown,onIdeas,onDraft,onGenerate,disabled}:{observations:number;families:number;unknown:number;onIdeas:(text:string)=>void;onDraft:(text:string)=>void;onGenerate:()=>void;disabled:boolean}){
 const [conversation,setConversation]=useState<Conversation|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(false),[audio,setAudio]=useState(false),[error,setError]=useState("");
 const end=useRef<HTMLDivElement>(null),started=useRef(false),ideasCallback=useRef(onIdeas);
 useEffect(()=>{ideasCallback.current=onIdeas;},[onIdeas]);
 const call=useCallback(async (body?:unknown)=>{const r=await apiFetch(`${localDatabaseApiUrl}/api/annual-journey/conversation`,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const value=await r.json() as Conversation & {error?:string};if(!r.ok)throw new Error(value.error??"No pude abrir la conversación. Puedes volver a intentarlo.");return value as Conversation;},[]);
 const open=useCallback(async ()=>{setBusy(true);setError("");try{let value:Conversation;try{value=await call();}catch{value=await call({});}if(value.status==="interrupted")value=await call({});setConversation(value);ideasCallback.current(value.teacherIdeas);}catch(e){setError(e instanceof Error?e.message:"No pude abrir la conversación.");}finally{setBusy(false);}},[call]);
 useEffect(()=>{if(started.current)return;started.current=true;void open();},[open]);
 useEffect(()=>{end.current?.scrollIntoView({block:"nearest",behavior:"instant"});},[conversation]);
 async function send(value=text){if(!conversation||!value.trim()||busy||audio)return;setBusy(true);setError("");try{const next=await call({id:conversation.id,expectedRevision:conversation.revision,text:value.trim()});setConversation(next);setText("");onDraft("");onIdeas(next.teacherIdeas);}catch(e){setError(e instanceof Error?e.message:"Tu respuesta sigue aquí. Vuelve a intentar.");}finally{setBusy(false);}}
 useEffect(()=>{if(conversation?.status!=="responding")return;const timer=window.setTimeout(()=>{void call().then(value=>{setConversation(value);ideasCallback.current(value.teacherIdeas);if(value.status==="interrupted")setError("La respuesta se interrumpió. Abre la conversación guardada para reintentar.");}).catch(()=>setError("No pude recuperar la respuesta. La conversación se conserva."));},2000);return()=>window.clearTimeout(timer);},[conversation,call]);
 const responding=conversation?.status==="responding";
 const ready=conversation?.status==="ready";
 return <div className="space-y-5"><JourneySteps active={4}/><div className="grid min-w-0 gap-5 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Información para el plan</h2><dl className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-1">{[[NotebookPen,"Observaciones",`${observations} registros`],[Users,"Familias",`${families} entrevistas`],[MessageCircle,"Todavía conocemos poco",`${unknown} competencias`],[MessageCircle,"Decisiones tuyas",`${conversation?.messages.filter(m=>m.role==="teacher").length??0} respuestas`]].map(([Icon,label,value])=>{const Glyph=Icon as typeof MessageCircle;return <div key={String(label)} className="flex items-center gap-3 rounded-xl border border-[#e1ebf0] p-3"><Glyph className="size-6 shrink-0 text-[#087d96]"/><div><dt className="text-sm font-bold">{String(label)}</dt><dd className="mt-1 text-sm text-[#526b87]">{String(value)}</dd></div></div>;})}</dl><p className="mt-5 text-xs leading-relaxed text-[#526b87]">Conocer poco no significa dificultad. Tus decisiones orientan el plan y conservan su procedencia.</p></aside><section aria-label="Conversación con Ayni" className="min-w-0 rounded-2xl bg-[#edf7fa] p-4 sm:p-6"><div role="log" aria-live="polite" aria-label="Mensajes" className="max-h-[440px] space-y-5 overflow-y-auto pr-1">{conversation?.messages.map((m,i)=><div key={i} className={`flex items-start gap-3 ${m.role==="teacher"?"justify-end":""}`}>{m.role==="assistant"&&<span className="hidden sm:block"><AyniMascot/></span>}<p className={`max-w-xl whitespace-pre-wrap rounded-2xl p-4 text-base leading-relaxed ${m.role==="teacher"?"bg-white text-[#172b52]":"bg-[#deeff4] text-[#172b52]"}`}>{m.text}</p></div>)}{(!conversation||responding)&&!error&&<p role="status" className="py-12 text-center text-[#526b87]">Ayni está revisando lo que ya conocemos…</p>}<div ref={end}/></div>
 {conversation?.chips.length&& !ready?<div className="my-4 flex flex-wrap gap-2">{conversation.chips.map(chip=><Button key={chip} variant="outline" className="max-w-full whitespace-normal text-left" disabled={busy||responding||audio||disabled} onClick={()=>{setText(chip);onDraft(chip);}}>{chip}</Button>)}</div>:null}
 {ready&&<div className="my-5 rounded-xl bg-white p-4"><h3 className="font-bold">Tus decisiones adicionales</h3><p className="mt-2 whitespace-pre-wrap text-sm">{conversation.teacherIdeas||"Prepararemos el año con los registros y el currículo disponibles."}</p><p className="mt-2 text-xs text-[#526b87]">Son decisiones docentes; no confirman intereses de todo el grupo.</p><Button className="mt-4 min-h-12" disabled={disabled||busy||audio||!!text.trim()} onClick={onGenerate}>Preparar mi año →</Button></div>}
 <div className="mt-5 rounded-xl bg-white p-4"><label htmlFor="annual-conversation-answer" className="text-sm font-semibold">{ready?"Puedes agregar una decisión concreta antes de preparar":"Tu respuesta para Ayni"}</label><Textarea id="annual-conversation-answer" value={text} maxLength={1600} disabled={busy||responding||disabled} onChange={e=>{setText(e.target.value);onDraft(e.target.value);}} placeholder="Escribe tu respuesta…" className="mt-2 min-h-20 border-0 shadow-none"/><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><DictationRecorder classroomScope purpose="group_summary" rawTranscript context="Decisiones docentes para el año" currentText={text} onTranscribed={t=>{setText(t.slice(0,1600));onDraft(t.slice(0,1600));}} onBusyChange={setAudio} disabled={busy||responding||disabled}/><Button disabled={busy||responding||audio||disabled||!text.trim()||!conversation} onClick={()=>void send()}><Send className="size-4"/>{busy?"Ayni está respondiendo…":"Enviar"}</Button></div></div>
 {error&&<div role="alert" className="mt-4 rounded-xl bg-[#fff1d6] p-4 text-sm">{error}<Button variant="outline" className="mt-3" disabled={busy} onClick={()=>void open()}>Abrir conversación guardada</Button></div>}
 <p className="mt-3 text-xs text-[#526b87]">{conversation?`${conversation.calls} respuestas de Luna · ${conversation.attempts} llamadas, incluidos reintentos · recargar conserva la conversación.`:"La conversación se guarda para retomarla."}</p></section></div></div>;
}
