"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Send, MessageCircle, Users, NotebookPen, Lightbulb, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiFetch, apiJson } from "@/src/lib/ayni-api-fetch";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
import { DictationRecorder } from "./dictation-recorder";
import { JourneySteps } from "./initial-journey-ui";
import { AyniChatMessage, AyniTyping } from "./ayni-chat-message";
type Conversation={id:string;revision:number;status:string;messages:{role:string;text:string}[];chips:string[];teacherIdeas:string;contextItems?:{text:string;source_turn:number}[]};
export function AnnualPlanningConversation({observations,families,unknown,onIdeas,onDraft,onGenerate,onConversation,disabled}:{observations:number;families:number;unknown:number;onIdeas:(text:string)=>void;onDraft:(text:string)=>void;onGenerate:()=>void;onConversation?:(value:{id:string;messages:{role:string;text:string}[];contextItems?:{text:string;source_turn:number}[]})=>void;disabled:boolean}){
 const [conversation,setConversation]=useState<Conversation|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(false),[audio,setAudio]=useState(false),[error,setError]=useState("");
 const [pending,setPending]=useState("");
 const [pendingIndex,setPendingIndex]=useState(0);
 const end=useRef<HTMLDivElement>(null),started=useRef(false),ideasCallback=useRef(onIdeas);
 useEffect(()=>{ideasCallback.current=onIdeas;},[onIdeas]);
 const call=useCallback(async (body?:unknown)=>{const r=await apiFetch(`${localDatabaseApiUrl}/api/annual-journey/conversation`,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const value=await apiJson<Conversation & {error?:string}>(r);if(!r.ok)throw Object.assign(new Error(value.error??"No pude abrir la conversación. Puedes volver a intentarlo."),{status:r.status});return value as Conversation;},[]);
 const open=useCallback(async ()=>{setBusy(true);setError("");try{let value:Conversation;try{value=await call();}catch(e){if((e as Error & {status?:number}).status!==404&&(e as Error & {status?:number}).status!==409)throw e;value=await call({});}if(value.status==="interrupted")value=await call({});setConversation(value);ideasCallback.current(value.teacherIdeas);setPending("");}catch(e){setError(e instanceof Error?e.message:"No pude abrir la conversación.");}finally{setBusy(false);}},[call]);
 useEffect(()=>{if(started.current)return;started.current=true;void open();},[open]);
 useEffect(()=>{end.current?.scrollIntoView({block:"nearest",behavior:"instant"});},[conversation,pending,busy]);
 async function send(value=text){if(!conversation||!value.trim()||busy||audio)return;const sent=value.trim();setPendingIndex(conversation.messages.length);setPending(sent);setConversation({...conversation,status:"responding"});setText("");onDraft("");setBusy(true);setError("");try{const next=await call({id:conversation.id,expectedRevision:conversation.revision,text:sent});setConversation(next);setPending("");onIdeas(next.teacherIdeas);}catch(e){try{const saved=await call();setConversation(saved);onIdeas(saved.teacherIdeas);if(saved.messages.slice(conversation.messages.length).some(m=>m.role==="teacher"&&m.text===sent)){setPending("");if(saved.status==="responding")return;setError(saved.status==="interrupted"?"Tu respuesta quedó guardada. Pulsa Retomar respuesta para continuar.":"");return;}}catch{/* Keep the unsent text available. */}setPending("");setText(sent);onDraft(sent);setError(e instanceof Error?e.message:"Tu respuesta sigue aquí. Vuelve a intentar.");}finally{setBusy(false);}}
 useEffect(()=>{if(!busy&&conversation?.status!=="responding")return;let live=true;let timer:number;const poll=async()=>{try{const value=await call();if(live){setConversation(value);ideasCallback.current(value.teacherIdeas);if(value.status!=="responding"&&!busy){setPending("");if(value.status==="interrupted")setError("Tu respuesta quedó guardada. Pulsa Retomar respuesta para continuar.");return;}}}catch{/* Read again without resending the teacher's message. */}if(live)timer=window.setTimeout(()=>void poll(),2500);};timer=window.setTimeout(()=>void poll(),2500);return()=>{live=false;window.clearTimeout(timer);};},[busy,conversation?.status,call]);
 useEffect(()=>{if(conversation)onConversation?.(conversation);},[conversation,onConversation]);
 const responding=conversation?.status==="responding";
 const ready=conversation?.status==="ready"&&!busy;
 return <div className="space-y-5"><JourneySteps active={4}/><div className="grid min-w-0 gap-5 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Información para el plan</h2><dl className="mt-5 grid grid-cols-2 gap-4 lg:grid-cols-1">{[[NotebookPen,"Observaciones",`${observations} registros`],[Users,"Familias",`${families} entrevistas`],[Lightbulb,"Con pocos registros",`${unknown} competencias`],[Target,"Decisiones tuyas",`${conversation?.messages.filter(m=>m.role==="teacher").length??0} ${conversation?.messages.filter(m=>m.role==="teacher").length===1?"respuesta":"respuestas"}`]].map(([Icon,label,value],i)=>{const Glyph=Icon as typeof MessageCircle;return <div key={String(label)} className="flex items-center gap-3 rounded-xl border border-[#e1ebf0] p-3"><span className={`grid size-14 shrink-0 place-items-center rounded-2xl ${["bg-[#dcf7ee] text-[#009982]","bg-[#e2efff] text-[#3572d7]","bg-[#fff2d8] text-[#de971a]","bg-[#efe5ff] text-[#9158dd]"][i]}`}><Glyph className="size-7"/></span><div><dt className="text-sm font-bold">{String(label)}</dt><dd className="mt-1 text-sm text-[#526b87]">{String(value)}</dd></div></div>;})}</dl><p className="mt-5 text-xs leading-relaxed text-[#526b87]">Conocer poco no significa dificultad. Tus decisiones orientan el plan y conservan su procedencia.</p></aside><section aria-label="Conversación con Ayni" className="min-w-0 rounded-2xl bg-[#edf7fa] p-4 sm:p-6"><div role="log" aria-live="polite" aria-label="Mensajes" className="max-h-[440px] space-y-5 overflow-y-auto pr-1">{conversation?.messages.map((m,i)=><AyniChatMessage key={i} role={m.role} text={m.text}/>)}{pending&&!conversation?.messages.slice(pendingIndex).some(m=>m.role==="teacher"&&m.text===pending)&&<AyniChatMessage role="teacher" text={pending}/>} {(busy||responding)&&!error&&<AyniTyping/>}<div ref={end}/></div>
 {conversation?.chips.length&& !ready?<div className="my-4 flex flex-wrap gap-2">{conversation.chips.map(chip=><Button key={chip} variant="outline" className="max-w-full whitespace-normal text-left" disabled={busy||responding||audio||disabled} onClick={()=>{setText(chip);onDraft(chip);}}>{chip}</Button>)}</div>:null}
 {ready&&<div className="my-5 rounded-xl bg-white p-4"><h3 className="font-bold">Ya tengo suficiente información para preparar tu año</h3><p className="mt-3 text-sm font-semibold">Tus decisiones docentes</p><p className="mt-2 whitespace-pre-wrap text-sm">{conversation.teacherIdeas.length>300?conversation.teacherIdeas.slice(0,300)+"…":conversation.teacherIdeas||"Prepararemos el año con los registros y el currículo disponibles."}</p>{conversation.teacherIdeas.length>300&&<details className="mt-2 text-sm"><summary className="cursor-pointer text-[#087d96]">Ver todas tus decisiones</summary><p className="mt-2 whitespace-pre-wrap">{conversation.teacherIdeas}</p></details>}<p className="mt-2 text-xs text-[#526b87]">Son decisiones docentes; no confirman intereses de todo el grupo.</p></div>}
 <div className="mt-5 rounded-xl bg-white p-4"><label htmlFor="annual-conversation-answer" className="text-sm font-semibold">{ready?"Puedes agregar una decisión concreta antes de preparar":"Tu respuesta para Ayni"}</label><div className="mt-2 flex items-start gap-2"><Textarea id="annual-conversation-answer" value={text} maxLength={1600} disabled={busy||responding||disabled} onChange={e=>{setText(e.target.value);onDraft(e.target.value);}} placeholder="Escribe tu respuesta…" className="min-h-20 min-w-0 flex-1 border-0 shadow-none"/><DictationRecorder iconOnly autoTranscribe classroomScope purpose="group_summary" rawTranscript context="Decisiones docentes para el año" currentText={text} onTranscribed={t=>{setText(t.slice(0,1600));onDraft(t.slice(0,1600));}} onBusyChange={setAudio} disabled={busy||responding||disabled}/><Button size="icon" className="size-12 shrink-0 rounded-full" aria-label={busy?"Ayni está respondiendo":"Enviar respuesta"} title="Enviar respuesta" disabled={busy||responding||audio||disabled||!text.trim()||!conversation} onClick={()=>void send()}><Send className="size-5"/></Button></div></div>
 {error&&<div role="alert" className="mt-4 rounded-xl bg-[#fff1d6] p-4 text-sm">{error}<Button variant="outline" className="mt-3" disabled={busy} onClick={()=>void open()}>{conversation?.status==="interrupted"?"Retomar respuesta":"Abrir conversación guardada"}</Button></div>}
 <Button className="mt-4 min-h-12" disabled={disabled||audio||!!text.trim()} onClick={onGenerate}>Crear Mi año con lo que ya sabes</Button><p className="mt-3 text-xs text-[#526b87]">Tu conversación queda guardada para retomarla. El diagnóstico es opcional: puedes crear tu año y seguir registrando después.</p></section></div></div>;
}
