"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Experience = { period: string; experience_type: "project" | "unit" | "workshop"; title: string; rationale: string; primary_competency_ids: string[]; possible_secondary_competency_ids: string[]; context_or_trigger: string; expected_evidence_categories: string[]; flexibility_notes: string };
type Proposal = { title: string; general_context_summary: string; proposed_experiences: Experience[] };
export function AnnualPlanGenerator() {
  const [proposal, setProposal] = useState<Proposal | null>(null); const [working, setWorking] = useState(false); const [message, setMessage] = useState(""); const [planId, setPlanId] = useState<string | null>(null);
  async function generate() { setWorking(true); setMessage(""); try { const response=await fetch("http://127.0.0.1:8788/api/ai/annual-plan/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({})}); const data=await response.json() as { proposal?: Proposal; error?: string; id?: string }; if(!response.ok) throw new Error(data.error); setProposal(data.proposal ?? null); } catch(error) { setMessage(error instanceof Error?error.message:"No pudimos generar una propuesta válida."); } finally { setWorking(false); } }
  async function save() { const response=await fetch("http://127.0.0.1:8788/api/annual-plans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({proposal})}); const data=await response.json() as { proposal?: Proposal; error?: string; id?: string }; if(!response.ok) { setMessage(data.error ?? "No se pudo guardar el borrador."); return; } setPlanId(data.id ?? null); setMessage("Borrador guardado. Aún no está confirmado."); }
  async function confirm() { if(!planId)return; const response=await fetch(`http://127.0.0.1:8788/api/annual-plans/${planId}/confirm`,{method:"POST"}); const data=await response.json() as { proposal?: Proposal; error?: string; id?: string }; setMessage(response.ok?"Plan anual confirmado por la docente.":(data.error ?? "No se pudo confirmar el plan.")); }
  return <section className="mx-auto max-w-4xl space-y-5"><header><p className="text-sm font-semibold text-[#087d96]">Planificar · Plan anual</p><h1 className="text-3xl font-bold">Plan anual</h1><p className="mt-2 text-muted-foreground">La propuesta usa el aula, edad, calendario y diagnóstico disponible. Puedes modificarla antes de confirmar.</p></header><Button disabled={working} onClick={()=>void generate()}>{working?"Preparando tu plan anual...":"Generar propuesta de plan anual"}</Button>{message&&<p role="status" className="text-sm">{message}</p>}{proposal&&<section className="space-y-4 rounded-2xl border bg-[#fbf9ff] p-5"><p className="font-bold text-[#7652bc]">Propuesta generada con IA. Puedes modificarla antes de confirmar.</p><label className="block">Título<Textarea value={proposal.title} onChange={e=>setProposal({...proposal,title:e.target.value})}/></label><label className="block">Resumen del contexto<Textarea value={proposal.general_context_summary} onChange={e=>setProposal({...proposal,general_context_summary:e.target.value})}/></label><div className="space-y-3">{proposal.proposed_experiences.map((item,index)=><article key={index} className="rounded-xl border bg-white p-3"><input className="w-full font-semibold" value={item.title} onChange={e=>{const next=[...proposal.proposed_experiences];next[index]={...item,title:e.target.value};setProposal({...proposal,proposed_experiences:next});}}/><select value={item.experience_type} onChange={e=>{const next=[...proposal.proposed_experiences];next[index]={...item,experience_type:e.target.value as Experience["experience_type"]};setProposal({...proposal,proposed_experiences:next});}}><option value="project">Proyecto</option><option value="unit">Unidad</option><option value="workshop">Taller</option></select><Button variant="ghost" onClick={()=>setProposal({...proposal,proposed_experiences:proposal.proposed_experiences.filter((_,i)=>i!==index)})}>Eliminar</Button></article>)}</div><Button variant="outline" onClick={()=>setProposal({...proposal,proposed_experiences:[...proposal.proposed_experiences,{period:"Por definir",experience_type:"workshop",title:"Nueva experiencia",rationale:"Por revisar",primary_competency_ids:[],possible_secondary_competency_ids:[],context_or_trigger:"Por definir",expected_evidence_categories:[],flexibility_notes:"Revisable"}]})}>Agregar experiencia</Button><div className="flex gap-3"><Button onClick={()=>void save()}>Guardar borrador</Button><Button disabled={!planId} onClick={()=>void confirm()}>Confirmar plan anual</Button></div></section>}</section>;
}
