"use client";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiFetch } from "@/src/lib/ayni-api-fetch";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
import { AsyncButton, WorkflowFeedback } from "./workflow-ui";

type Entry={competency_id:string;assessment_focus:string;relevant_evidence:string[];patterns_to_consider:string[];progress_signals:string[];support_signals:string[];insufficient_information_rules:string[];contradiction_handling:string;context_considerations:string[];teacher_questions:string[];prohibited_inferences:string[];assessment_guidance:string};
type Proposal={period_summary:string;competencies:Entry[]};
type Master={id:string;version:number;status:"draft"|"active"|"archived";details:Proposal;stale:boolean};
const arrays=["relevant_evidence","patterns_to_consider","progress_signals","support_signals","insufficient_information_rules","context_considerations","teacher_questions","prohibited_inferences"] as const;
const labels:Record<string,string>={assessment_focus:"Qué se revisará",relevant_evidence:"Evidencias relevantes",patterns_to_consider:"Patrones a considerar",progress_signals:"Señales de progreso",support_signals:"Señales de apoyo necesario",insufficient_information_rules:"Cuándo falta información",contradiction_handling:"Cómo tratar diferencias entre evidencias",context_considerations:"Contexto permitido",teacher_questions:"Preguntas para la docente",prohibited_inferences:"Qué no se debe inferir",assessment_guidance:"Guía para interpretar"};

export function AssessmentMasterPanel({periodId,onReady}:{periodId:string;onReady?:(ready:boolean)=>void}){
 const [master,setMaster]=useState<Master|null>(null),[proposal,setProposal]=useState<Proposal|null>(null),[generationId,setGenerationId]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const fetchMaster=useCallback(async()=>{if(!periodId)return null;const r=await apiFetch(`${localDatabaseApiUrl}/api/assessment-masters?periodId=${periodId}`);const d=await r.json() as {current:Master|null;error?:string};if(!r.ok)throw new Error(d.error);return d.current;},[periodId]);
 const applyMaster=useCallback((current:Master|null)=>{setMaster(current);setProposal(current?.status==="draft"?current.details:null);onReady?.(current?.status==="active"&&!current.stale);},[onReady]);
 const load=useCallback(async()=>applyMaster(await fetchMaster()),[applyMaster,fetchMaster]);
 useEffect(()=>{let cancelled=false;void fetchMaster().then((current)=>{if(!cancelled)applyMaster(current);}).catch((e)=>{if(!cancelled)setMessage(e instanceof Error?e.message:"No se pudo cargar el marco.");});return()=>{cancelled=true;};},[applyMaster,fetchMaster]);
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage("");try{await fn();}catch(e){setMessage(e instanceof Error?e.message:"No se pudo completar la acción.");}finally{setBusy(false);}}
 async function generate(){await act(async()=>{const r=await apiFetch(`${localDatabaseApiUrl}/api/ai/assessment-masters/generate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({periodId})});const d=await r.json() as {proposal?:Proposal;generation_id?:string;error?:string};if(!r.ok||!d.proposal||!d.generation_id)throw new Error(d.error??"No se pudo preparar el marco.");setProposal(d.proposal);setGenerationId(d.generation_id);setMessage("Marco preparado. Revísalo antes de guardar.");});}
 async function save(){if(!proposal)return;await act(async()=>{const generated=Boolean(generationId);const path=!generated&&master?.status==="draft"?`/api/assessment-masters/${master.id}`:"/api/assessment-masters";const r=await apiFetch(`${localDatabaseApiUrl}${path}`,{method:!generated&&master?.status==="draft"?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(!generated&&master?.status==="draft"?{proposal}:{periodId,proposal,generationId})});const d=await r.json() as {id?:string;version?:number;error?:string};if(!r.ok||!d.id)throw new Error(d.error);setMaster({id:d.id,version:d.version??master?.version??1,status:"draft",details:proposal,stale:false});setGenerationId(null);setMessage("Borrador guardado.");});}
 async function confirm(){if(!master||master.status!=="draft")return;await act(async()=>{const r=await apiFetch(`${localDatabaseApiUrl}/api/assessment-masters/${master.id}/confirm`,{method:"POST"});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();setProposal(null);setMessage("Marco confirmado. Ya puedes pedir sugerencias por niño.");});}
 async function copy(){if(!master)return;await act(async()=>{const r=await apiFetch(`${localDatabaseApiUrl}/api/assessment-masters/${master.id}/copy`,{method:"POST"});const d=await r.json() as {id?:string;version?:number;details?:Proposal;error?:string};if(!r.ok||!d.id||!d.details)throw new Error(d.error);setMaster({id:d.id,version:d.version??master.version+1,status:"draft",details:d.details,stale:false});setProposal(d.details);});}
 const edit=(i:number,key:keyof Entry,value:string)=>{if(!proposal)return;const list=[...proposal.competencies],row={...list[i]};(row as unknown as Record<string,unknown>)[key]=(arrays as readonly string[]).includes(key)?value.split("\n").map(x=>x.trim()).filter(Boolean):value;list[i]=row;setProposal({...proposal,competencies:list});};
 return <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Marco de evaluación del período</h3><p className="mt-1 text-sm text-[#526b87]">Ayni lo prepara una vez con las competencias realmente trabajadas. Luego lo aplica a cada niño; tú confirmas cada valoración.</p>{message&&<WorkflowFeedback tone={message.includes("No ")||message.includes("cambió")?"error":"success"}>{message}</WorkflowFeedback>}
 {!master&&!proposal&&<AsyncButton className="mt-3" busy={busy} busyLabel="Preparando marco..." onClick={()=>void generate()}>Preparar marco del período</AsyncButton>}
 {master?.status==="active"&&!proposal&&<div className="mt-3"><p className={master.stale?"rounded-xl bg-[#fff2d9] p-3 text-sm":"rounded-xl bg-[#e6f9ef] p-3 text-sm"}>{master.stale?"La planificación o los criterios cambiaron. Prepara una versión actualizada.":`Marco V${master.version} confirmado.`}</p><div className="mt-2 flex gap-2">{master.stale&&<AsyncButton busy={busy} busyLabel="Actualizando..." onClick={()=>void generate()}>Actualizar marco</AsyncButton>}<Button variant="outline" disabled={busy} onClick={()=>void copy()}>Editar nueva versión</Button></div></div>}
 {proposal&&<div className="mt-4 space-y-4"><label className="block text-sm font-semibold">Síntesis del período<Textarea className="mt-1" value={proposal.period_summary} onChange={e=>setProposal({...proposal,period_summary:e.target.value})}/></label>{proposal.competencies.map((row,i)=><details key={row.competency_id} className="rounded-xl border p-3"><summary className="cursor-pointer font-semibold">{row.competency_id}</summary><div className="mt-3 space-y-3">{Object.keys(labels).map(key=><label key={key} className="block text-sm font-semibold">{labels[key]}<Textarea className="mt-1" value={Array.isArray(row[key as keyof Entry])?(row[key as keyof Entry] as string[]).join("\n"):String(row[key as keyof Entry])} onChange={e=>edit(i,key as keyof Entry,e.target.value)}/></label>)}</div></details>)}<div className="flex flex-wrap gap-2"><AsyncButton busy={busy} busyLabel="Guardando..." onClick={()=>void save()}>Guardar marco</AsyncButton>{master?.status==="draft"&&!generationId&&<AsyncButton busy={busy} busyLabel="Confirmando..." onClick={()=>void confirm()}>Confirmar marco</AsyncButton>}</div></div>}
 </section>;
}
