"use client";
import { useEffect, useState } from "react";
import { Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { apiFetch } from "@/src/lib/ayni-api-fetch";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
import { annualDisplayTitle } from "@/src/lib/annual-year-editor.mjs";
import { DictationRecorder } from "./dictation-recorder";
import { ProjectPictogram } from "./project-pictogram";
type Candidate={purpose:string;invitation:string;materials:string[];supports:string[];flexibility:string;source_fact_keys:string[];opportunities:{competency_id:string;capacity_names:string[];child_action:string;conditions:string;mediation:string;observation:string;supports:string}[];proposal_id:string;title:string;rationale:string;children_actions:string[];primary_competency_ids:string[]};
type Session={id:string;revision:number;status:string;messages:{role:string;text:string}[];candidate:Candidate|null;candidate_sources:{key:string;text:string}[]};
export function NewAnnualProposal({open,onOpenChange,planId,revision,onApproved,curriculumReference=[]}:{open:boolean;onOpenChange:(open:boolean)=>void;planId:string;revision:number;onApproved:(id:string)=>Promise<unknown>;curriculumReference?:{id:string;name:string}[]}) {
  const [session,setSession]=useState<Session|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(false),[audio,setAudio]=useState(false),[error,setError]=useState(""),[type,setType]=useState("project");
  useEffect(()=>{if(!open)return;let live=true;
    const start=async()=>{
      setBusy(true);setError("");
      try {const r=await apiFetch(`${localDatabaseApiUrl}/api/annual-journey/${planId}/new-proposal/conversation`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedRevision:revision})});const data=await r.json() as Session & {error?:string};if(!r.ok)throw Error(data.error ?? "No pudimos abrir la conversación.");if(live)setSession(data);}
      catch(e){if(live)setError(e instanceof Error?e.message:"No pudimos abrir la conversación.");}finally{if(live)setBusy(false);}
    };void start();return()=>{live=false;};
  },[open,planId,revision]);
  const call=async(operation:string,restart=false)=>{
    if(busy||audio)return;setBusy(true);setError("");
    try {const r=await apiFetch(`${localDatabaseApiUrl}/api/annual-journey/${planId}/new-proposal/${operation}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedRevision:revision,...(!restart&&session?{id:session.id,revision:session.revision}:{}),...(operation==="conversation"&&text.trim()?{text}:{}),experienceType:type,restart})});const data=await r.json() as Session & {error?:string};if(!r.ok)throw Error(data.error ?? "No se completó la propuesta.");
      if(operation==="approve"){await onApproved(data.id);setSession(null);setText("");onOpenChange(false);}else {setSession(data);if(operation==="conversation")setText("");}
    }catch(e){setError(e instanceof Error?e.message:"No se completó la propuesta.");}finally{setBusy(false);}
  };
  const competencyName=(id:string)=>curriculumReference.find(c=>c.id===id)?.name ?? id;
  return <Sheet open={open} onOpenChange={value=>{if(!value&&(busy||audio))return;if(!value&&text.trim()&&!window.confirm("Hay una respuesta sin enviar. ¿Quieres cerrar este panel?"))return;onOpenChange(value);}}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>Nueva propuesta con Ayni</SheetTitle><SheetDescription>Una conversación breve para preparar una alternativa. Aparecerá en Biblioteca cuando la revises y apruebes.</SheetDescription></SheetHeader><div className="space-y-5 px-5 pb-6">
    <div role="log" aria-live="polite" className="space-y-4">{session?.messages.map((m,i)=><p key={i} className={`whitespace-pre-wrap rounded-xl p-4 leading-relaxed ${m.role==="teacher"?"ml-8 bg-white border border-[#d6e5ef]":"mr-5 bg-[#edf7fa]"}`}>{m.text}</p>)}</div>
    {error&&<div role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><p>{error}</p><Button className="mt-3" variant="outline" disabled={busy} onClick={()=>void call("conversation",true)}>Abrir una conversación nueva</Button></div>}
    {busy&&<p role="status" className="text-sm text-[#526b87]">Ayni está preparando lo que necesitas. La conversación se conserva.</p>}
    {!session?.candidate&&<><label className="block text-sm font-semibold" htmlFor="new-proposal-answer">Tu idea para esta propuesta</label><div className="flex items-start gap-2"><Textarea id="new-proposal-answer" value={text} onChange={e=>setText(e.target.value)} disabled={busy||audio} maxLength={1600} className="min-h-24 min-w-0 flex-1" placeholder="Por ejemplo, un proyecto sobre el mercado…"/><DictationRecorder iconOnly autoTranscribe classroomScope purpose="group_summary" rawTranscript context="Intención docente para una nueva propuesta anual" currentText={text} onTranscribed={value=>setText(value.slice(0,1600))} onBusyChange={setAudio} disabled={busy}/><Button size="icon" className="size-12 shrink-0 rounded-full" aria-label="Enviar idea" disabled={busy||audio||!text.trim()||!session} onClick={()=>void call("conversation")}><Send className="size-5"/></Button></div></>}
    {session?.status==="ready"&&!session.candidate&&<div className="space-y-3 rounded-xl bg-[#edf7fa] p-4"><h3 className="font-bold">Ya puedo preparar esta propuesta</h3><p className="text-sm">Ayni preparará y revisará solo esta alternativa, conservando el resto de Mi año.</p><label className="block text-sm">Tipo<select value={type} onChange={e=>setType(e.target.value)} disabled={busy} className="ml-3 min-h-11 rounded-lg border bg-white px-3"><option value="project">Proyecto</option><option value="unit">Unidad</option></select></label><Button disabled={busy||audio||!!text.trim()} onClick={()=>void call("generate")}>Preparar propuesta</Button></div>}
    {session?.candidate&&<article className="space-y-4 border-t border-[#d6e5ef] pt-5"><div className="flex items-center gap-4"><ProjectPictogram project={session.candidate} className="size-16"/><h3 className="text-xl font-bold">{annualDisplayTitle(session.candidate.title)}</h3></div><h4 className="font-semibold">Qué podrían hacer los niños</h4><ul className="list-disc space-y-2 pl-5">{session.candidate.children_actions.map((v,i)=><li key={i}>{v}</li>)}</ul><h4 className="font-semibold">Por qué tiene sentido</h4><p>{session.candidate.rationale}</p><div><h4 className="font-semibold">Competencias</h4><ul className="mt-2 list-disc pl-5 text-sm">{session.candidate.primary_competency_ids.map(id=><li key={id}>{competencyName(id)}</li>)}</ul></div><details className="text-sm leading-relaxed"><summary className="min-h-11 cursor-pointer py-2 font-semibold text-[#087d96]">Ver detalles</summary><div className="space-y-4 py-3"><div><h4 className="font-semibold">Propósito</h4><p>{session.candidate.purpose}</p></div><div><h4 className="font-semibold">Invitación</h4><p>{session.candidate.invitation}</p></div><div><h4 className="font-semibold">Materiales</h4><ul className="list-disc pl-5">{session.candidate.materials.map((v,i)=><li key={i}>{v}</li>)}</ul></div><div><h4 className="font-semibold">Apoyos y flexibilidad</h4><ul className="list-disc pl-5">{session.candidate.supports.map((v,i)=><li key={i}>{v}</li>)}</ul><p>{session.candidate.flexibility}</p></div><div><h4 className="font-semibold">Oportunidades curriculares</h4>{session.candidate.opportunities.map((o,i)=><div key={i} className="mt-3 space-y-1"><b>{competencyName(o.competency_id)}</b><p>{o.capacity_names.join(" · ")}</p><p>{o.child_action}</p><p>Condiciones: {o.conditions}</p><p>Mediación: {o.mediation}</p><p>Qué observar: {o.observation}</p><p>Apoyos: {o.supports}</p></div>)}</div><div><h4 className="font-semibold">Fuentes pertinentes</h4>{session.candidate_sources.map(f=><p className="mt-2" key={f.key}>{f.text}</p>)}</div></div></details><p className="text-sm text-[#526b87]">Esta propuesta todavía no tiene fechas. Después podrás elegir el tramo donde colocarla.</p><Button disabled={busy||audio} onClick={()=>void call("approve")}>Guardar en Biblioteca</Button></article>}
  </div></SheetContent></Sheet>;
}
