"use client";

import { useEffect,useMemo,useState } from "react";
import { CalendarDays,ChevronLeft,ChevronRight,Clock3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiFetch } from "@/src/lib/ayni-api-fetch";
import { calendarWeekDays, calendarWeekLabel, navigateCalendarPeriod } from "@/src/lib/school-calendar-navigation.mjs";
import { useWorkspaceSubview } from "@/src/lib/workspace-location";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
import { LoadingState,WorkflowFeedback } from "./workflow-ui";

type Day={id:string;date:string;calendar_type:string;is_instructional:boolean;source:string;reason:string;editable:boolean;school_override:boolean};
type Experience={id:string;title:string;type:"project"|"unit"|"workshop";starts_on:string;ends_on:string;status:string;details?:{activity_route?:unknown[]}};
type Activity={id:string;title:string;purpose:string|null;occurs_on:string;planned_date:string|null;schedule_status:string;status:string;experience_id:string;experience_title:string;experience_type:string;details?:{competency_id?:string};start_time:string};
type CalendarData={classroom:{id:string;section:string;year:number;starts_on:string;ends_on:string};version:{name:string;version:string;source_name:string;source_url:string;source_metadata:Record<string,unknown>};days:Day[];blocks:{type:string;label:string;start_date:string;end_date:string;sort_order:number}[];experiences:Experience[];activities:Activity[]};

const dayKey=(date:Date)=>date.toISOString().slice(0,10);
const asDate=(value:string)=>new Date(`${value}T00:00:00Z`);
const todayKey=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Lima",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const shortDate=(value:string)=>new Intl.DateTimeFormat("es-PE",{day:"numeric",month:"short",timeZone:"UTC"}).format(asDate(value));
const longDate=(value:string)=>new Intl.DateTimeFormat("es-PE",{weekday:"long",day:"numeric",month:"long",timeZone:"UTC"}).format(asDate(value));
const reasonLabel=(day?:Day)=>!day?"Fuera del año escolar":day.calendar_type==="instructional_day"?"Día de clase":day.calendar_type==="weekend"?"Fin de semana":day.calendar_type==="national_holiday"?day.reason:day.calendar_type==="management_week"?"Semana de gestión":day.reason;
const color=(day?:Day)=>!day?"bg-slate-50 text-slate-400":day.calendar_type==="management_week"?"bg-[#f2eafd] text-[#6843a5]":day.calendar_type==="school_non_instructional"?"bg-[#fff4d9] text-[#8a5b08]":day.is_instructional?"bg-[#e8f7f0] text-[#236c57]":"bg-[#fff0f0] text-[#8f3c3c]";
const json=async<T,>(path:string,init?:RequestInit)=>{const response=await apiFetch(`${localDatabaseApiUrl}${path}`,init);const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error??"No se pudo cargar el calendario.");return body;};

const calendarViews = ["month", "week", "year"] as const;
export function SchoolCalendarScreen({onOpenPlanning,onOpenActivity}:{onOpenPlanning:()=>void;onOpenActivity:(activity:{id:string;experience_id:string})=>void}){
  const [data,setData]=useState<CalendarData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const [view,setView]=useWorkspaceSubview("Calendario", "view", calendarViews, "month"),[selected,setSelected]=useState(todayKey());
  const [cursor,setCursor]=useState(()=>{const now=new Date();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));});
  const [reason,setReason]=useState(""),[reprogram,setReprogram]=useState<{id:string;date:string;reason:string}|null>(null);
  const [workshop,setWorkshop]=useState<Activity|null>(null);
  async function load(){setLoading(true);setError("");try{const next=await json<CalendarData>("/api/school-calendar");setData(next);const fallback=next.days.find((day)=>day.date===todayKey())?.date??next.days.find((day)=>day.is_instructional)?.date??next.days[0]?.date;if(fallback){setSelected(fallback);const date=asDate(fallback);setCursor(new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),1)));}}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo abrir el calendario.");}finally{setLoading(false);}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);
  const byDate=useMemo(()=>new Map(data?.days.map((day)=>[day.date,day])??[]),[data]);
  const monthDays=useMemo(()=>{const first=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth(),1)),last=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+1,0));const start=new Date(first);start.setUTCDate(start.getUTCDate()-((start.getUTCDay()+6)%7));const end=new Date(last);end.setUTCDate(end.getUTCDate()+(7-((end.getUTCDay()+6)%7)-1));const rows=[];for(const d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1))rows.push(dayKey(d));return rows;},[cursor]);
  const visibleDays=useMemo(()=>view==="week"?calendarWeekDays(selected):monthDays,[view,monthDays,selected]);
  const movePeriod=(direction:number)=>{const next=navigateCalendarPeriod(view,selected,cursor,direction);setSelected(next.selected);setCursor(next.cursor);};
  const selectedActivities=data?.activities.filter((item)=>item.occurs_on===selected)??[];
  const selectedDay=byDate.get(selected);
  const selectedLabel=reasonLabel(selectedDay);
  const selectedReason=selectedDay?.reason&&selectedDay.reason!==selectedLabel?` · ${selectedDay.reason}`:"";
  const today=todayKey();
  const currentProject=data?.experiences.find((item)=>item.type!=="workshop"&&item.starts_on<=today&&today<=item.ends_on&&item.status==="active");
  const nextProject=data?.experiences.filter((item)=>item.type!=="workshop"&&item.starts_on>today&&item.status==="active").sort((a,b)=>a.starts_on.localeCompare(b.starts_on))[0];
  const nextActivity=data?.activities.filter((item)=>item.occurs_on>=today&&!['cancelled','not_worked'].includes(item.schedule_status)).sort((a,b)=>a.occurs_on.localeCompare(b.occurs_on))[0];
  async function saveOverride(){if(!selectedDay?.editable||!reason.trim())return;try{await json("/api/school-calendar/override",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({date:selected,isInstructional:false,reason})});setReason("");await load();}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo cambiar el día.");}}
  async function saveReprogram(){if(!reprogram?.date||!reprogram.reason.trim())return;try{await json(`/api/activities/${reprogram.id}/reschedule`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({newDate:reprogram.date,reason:reprogram.reason,changeType:"rescheduled"})});setReprogram(null);await load();}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo reprogramar.");}}
  async function markNotWorked(activityId:string){try{await json(`/api/activities/${activityId}/reschedule`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason:"La docente indicó que la actividad no se realizó en la fecha prevista.",changeType:"not_worked"})});setReprogram(null);await load();}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo actualizar la actividad.");}}
  if(loading)return <LoadingState label="Preparando el calendario escolar..."/>;
  if(!data)return <WorkflowFeedback tone="error">{error||"Calendario no disponible."}</WorkflowFeedback>;
  const title=view==="week"?calendarWeekLabel(selected):new Intl.DateTimeFormat("es-PE",{month:"long",year:"numeric",timeZone:"UTC"}).format(cursor);
  const projectProgress=currentProject?{done:data.activities.filter((item)=>item.experience_id===currentProject.id&&item.status==="active"&&item.schedule_status!=="not_worked"&&item.occurs_on<today).length,total:data.activities.filter((item)=>item.experience_id===currentProject.id&&item.schedule_status!=="cancelled").length}:null;
  return <section className="mx-auto max-w-7xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#087d96]">Organización del año</p><h1 className="text-3xl font-extrabold text-[#172b52]">Calendario escolar</h1><p className="text-[#526b87]">Clases, proyectos y actividades en un mismo lugar.</p></div><div className="flex flex-wrap gap-2 [&_button]:min-h-11"><Button variant="outline" onClick={()=>{const d=asDate(today);setCursor(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)));setSelected(today);}}>Hoy</Button>{(["month","week","year"] as const).map((item)=><Button key={item} variant={view===item?"default":"outline"} onClick={()=>setView(item)}>{item==="month"?"Mes":item==="week"?"Semana":"Año"}</Button>)}</div></header>
    {error&&<WorkflowFeedback tone="error">{error}</WorkflowFeedback>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><main className="space-y-4"><section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-4"><Button variant="ghost" aria-label={view==="week"?"Semana anterior":view==="year"?"Año anterior":"Mes anterior"} onClick={()=>movePeriod(-1)}><ChevronLeft/></Button><h2 className="text-xl font-bold capitalize">{view==="year"?cursor.getUTCFullYear():title}</h2><Button variant="ghost" aria-label={view==="week"?"Semana siguiente":view==="year"?"Año siguiente":"Mes siguiente"} onClick={()=>movePeriod(1)}><ChevronRight/></Button></div>
      {view==="year"?<div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:12},(_,month)=>{const items=data.days.filter((day)=>asDate(day.date).getUTCFullYear()===cursor.getUTCFullYear()&&asDate(day.date).getUTCMonth()===month);return <button key={month} className="rounded-xl border p-4 text-left" onClick={()=>{setCursor(new Date(Date.UTC(cursor.getUTCFullYear(),month,1)));setView("month");}}><b className="capitalize">{new Intl.DateTimeFormat("es-PE",{month:"long",timeZone:"UTC"}).format(new Date(Date.UTC(cursor.getUTCFullYear(),month,1)))}</b><span className="mt-2 block text-sm text-[#526b87]">{items.filter((day)=>day.is_instructional).length} días de clase</span></button>})}</div>:
      <><div className="grid grid-cols-7 border-b bg-[#f4f8fb] text-center text-xs font-bold text-[#526b87]">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((day)=><div className="p-2" key={day}>{day}</div>)}</div><div className="grid grid-cols-7">{visibleDays.map((date)=>{const day=byDate.get(date),outside=asDate(date).getUTCMonth()!==cursor.getUTCMonth(),activities=data.activities.filter((item)=>item.occurs_on===date),projects=data.experiences.filter((item)=>item.starts_on<=date&&date<=item.ends_on&&item.status==="active");return <button key={date} type="button" onClick={()=>setSelected(date)} aria-label={`${longDate(date)}: ${reasonLabel(day)}${projects.length ? ` · ${projects.map((item)=>item.title).join(" · ")}` : ""}${activities.length ? ` · ${activities.length} actividades` : ""}`} className={`relative min-h-20 border-b border-r p-1 sm:min-h-28 sm:p-2 text-left align-top ${outside?"opacity-45":""} ${selected===date?"ring-2 ring-inset ring-[#087d96]":""} ${color(day)}`}><span className="font-bold">{date.slice(8)}</span><span className="mt-1 hidden text-xs leading-snug sm:block">{reasonLabel(day)}</span>{projects.length > 0 && <span className="mt-2 block size-2.5 rounded-full bg-[#344c8a] sm:hidden" aria-label="Proyecto programado"/>}{projects.slice(0,1).map((project)=><span key={project.id} className="mt-1 hidden break-words rounded bg-[#dfe7ff] px-1 py-0.5 text-xs leading-snug text-[#344c8a] sm:block">{project.title}</span>)}{activities.length>0&&<span className="absolute bottom-1 right-1 grid size-6 place-items-center rounded-full bg-[#087d96] text-xs font-bold text-white" aria-label={`${activities.length} actividades`}>{activities.length}</span>}</button>})}</div></>}</section>
      <div className="flex flex-wrap gap-3 text-sm"><span>🟢 Clase</span><span>🔴 Sin clases / feriado</span><span>🟣 Semana de gestión</span><span>🟡 Excepción del colegio</span><span>● Actividad programada</span><span className="flex items-center gap-2 sm:hidden"><span aria-hidden="true" className="size-2.5 rounded-full bg-[#344c8a]"/>Proyecto</span></div>
      <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold capitalize">{longDate(selected)}</h2><p className="mt-1 text-sm text-[#526b87]">{selectedLabel}{selectedReason}</p>{data.experiences.filter((item)=>item.starts_on<=selected&&selected<=item.ends_on&&item.status==="active").map((item)=><p key={item.id} className="mt-2 break-words text-sm font-semibold text-[#344c8a]">{item.title}</p>)}{selectedActivities.length?<div className="mt-4 space-y-3">{selectedActivities.map((activity)=><article key={activity.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{activity.title}</b><p className="text-sm text-[#526b87]">{activity.start_time?activity.start_time.slice(0,5):"Hora por definir"} · {activity.experience_title} · {activity.schedule_status==="rescheduled"?"Reprogramada":activity.schedule_status==="not_worked"?"No realizada":activity.status==="active"?"Confirmada":"Pendiente"}</p></div><Button variant="outline" onClick={()=>activity.experience_type==="workshop"?setWorkshop(activity):onOpenActivity(activity)}>Ver actividad</Button></div>{reprogram?.id===activity.id?<div className="mt-3 grid gap-2 sm:grid-cols-[150px_1fr_auto]"><div><label className="mb-1 block text-sm font-semibold" htmlFor={`reschedule-date-${activity.id}`}>Nueva fecha</label><Input id={`reschedule-date-${activity.id}`} type="date" value={reprogram.date} onChange={(event)=>setReprogram({...reprogram,date:event.target.value})}/></div><div><label className="mb-1 block text-sm font-semibold" htmlFor={`reschedule-reason-${activity.id}`}>Motivo de reprogramación</label><Input id={`reschedule-reason-${activity.id}`} placeholder="Motivo" value={reprogram.reason} onChange={(event)=>setReprogram({...reprogram,reason:event.target.value})}/></div><Button className="self-end" onClick={()=>void saveReprogram()}>Guardar</Button></div>:<div className="mt-2 flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setReprogram({id:activity.id,date:activity.occurs_on,reason:""})}>Reprogramar</Button>{activity.schedule_status!=="not_worked"&&<Button variant="ghost" onClick={()=>void markNotWorked(activity.id)}>Marcar como no realizada</Button>}</div>}</article>)}</div>:<p className="mt-4 rounded-xl bg-[#f4f8fb] p-4">No hay actividades programadas para este día.</p>}
      {workshop && <div role="dialog" aria-modal="true" aria-label="Actividad seleccionada" className="fixed inset-0 z-50 grid place-items-center bg-[#10233a]/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><p className="text-sm font-semibold text-[#087d96]">Taller · {longDate(workshop.occurs_on)}</p><h3 className="mt-2 text-xl font-bold">{workshop.title}</h3><p className="mt-1 text-sm text-[#526b87]">{workshop.experience_title} · {workshop.status==="active"?"Confirmada":"Pendiente"}</p>{workshop.purpose && <p className="mt-4">{workshop.purpose}</p>}<Button className="mt-5" onClick={()=>setWorkshop(null)}>Cerrar</Button></div></div>}
      {selectedDay?.is_instructional&&selectedDay.editable&&<div className="mt-4 border-t pt-4"><p className="font-semibold">Excepción del calendario del aula</p><div className="mt-2 flex flex-col gap-2 sm:flex-row"><div className="flex-1"><label className="mb-1 block text-sm font-semibold" htmlFor="calendar-exception-reason">Motivo de la excepción</label><Input id="calendar-exception-reason" value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Ej.: actuación por aniversario"/></div><Button className="self-end" variant="outline" disabled={!reason.trim()} onClick={()=>void saveOverride()}>Marcar sin clases</Button></div></div>}</section></main>
      <aside className="space-y-4"><section className="rounded-2xl border bg-white p-4"><CalendarDays className="mb-2 text-[#087d96]"/><h2 className="font-bold">{data.version.name}</h2><p className="text-xs text-[#526b87]">{data.version.version}</p><div className="mt-3 space-y-2">{data.blocks.map((block)=><div key={`${block.sort_order}-${block.label}`} className="rounded-lg bg-[#f4f8fb] p-2 text-sm"><b>{block.label}</b><span className="block text-xs">{shortDate(block.start_date)}–{shortDate(block.end_date)}</span></div>)}</div><a className="mt-3 inline-block text-sm font-bold text-[#087d96] underline" href={data.version.source_url} target="_blank" rel="noreferrer">Ver fuente oficial</a></section>
      <section className="rounded-2xl bg-[#eaf7fb] p-4"><h2 className="font-bold">Proyecto actual</h2>{currentProject?<><p className="mt-2 font-semibold">{currentProject.title}</p><p className="text-sm">{shortDate(currentProject.starts_on)}–{shortDate(currentProject.ends_on)}</p><p className="mt-2 text-sm">{projectProgress?.done??0} de {projectProgress?.total??0} actividades realizadas</p><Button className="mt-3" variant="outline" onClick={onOpenPlanning}>Abrir proyecto</Button></>:<p className="mt-2 text-sm">No hay un proyecto activo hoy.</p>}</section>
      <section className="rounded-2xl border bg-white p-4"><Clock3 className="mb-2 text-[#087d96]"/><h2 className="font-bold">Próxima actividad</h2><p className="mt-2 text-sm">{nextActivity?`${shortDate(nextActivity.occurs_on)} · ${nextActivity.title}`:"Aún no hay otra actividad programada."}</p><h2 className="mt-4 font-bold">Próximo proyecto</h2><p className="mt-2 text-sm">{nextProject?`${shortDate(nextProject.starts_on)} · ${nextProject.title}`:"Aún no hay otro proyecto confirmado."}</p></section></aside></div></section>;
}
