"use client";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { AyniMascot } from "@/src/features/dashboard/components/initial-journey-ui";
import { familyInterviewQuestionGroups, interviewInterestOptions, interviewSocialPlayOptions, interviewHomeActivityOptions, interviewLanguageOptions, interviewCommunityOptions, interviewParticipationSupportOptions } from "@/src/lib/family-interview-contract.mjs";
import type { FamilyInterviewDetails } from "@/src/lib/local-database";
import { localDatabaseApiUrl } from "@/src/lib/local-database";
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;onresult:((e:{results:{[key:number]:{[key:number]:{transcript:string}}}})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null};
export default function FamilyInterviewPage(){
  const [token,setToken]=useState(""),[name,setName]=useState(""),[details,setDetails]=useState<FamilyInterviewDetails>({}),[step,setStep]=useState(0),[message,setMessage]=useState(""),[loaded,setLoaded]=useState(false),[recording,setRecording]=useState(false);
  const recognition=useRef<Recognition|null>(null),saved=useRef(""),queue=useRef<Promise<unknown>>(Promise.resolve());
  async function api(method:string,body?:unknown){await queue.current.catch(()=>{});const r=await fetch(`${localDatabaseApiUrl}/api/family-share`,{method,headers:{"content-type":"application/json","x-ayni-family-token":token},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json() as {error?:string};if(!r.ok)throw new Error(value.error);return value;}
  useEffect(()=>{const value=new URLSearchParams(window.location.hash.slice(1)).get("token")??"";Promise.resolve().then(()=>setToken(value));return()=>recognition.current?.stop();},[]);
  useEffect(()=>{if(!token)return;fetch(`${localDatabaseApiUrl}/api/family-share`,{headers:{"x-ayni-family-token":token}}).then(async r=>{const v=await r.json() as {error?:string;name:string;details:FamilyInterviewDetails};if(!r.ok)throw new Error(v.error);setName(v.name);setDetails(v.details);saved.current=JSON.stringify(v.details);setLoaded(true);}).catch(e=>setMessage(e.message));},[token]);
  useEffect(()=>{if(!loaded||recording||JSON.stringify(details)===saved.current)return;const timer=window.setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(()=>fetch(`${localDatabaseApiUrl}/api/family-share`,{method:"PUT",headers:{"content-type":"application/json","x-ayni-family-token":token},body:JSON.stringify({details})}).then(r=>{if(!r.ok)throw new Error();saved.current=JSON.stringify(details);setMessage("Respuesta guardada.");})).catch(()=>setMessage("No pude guardar. Puedes volver a intentarlo; tu respuesta sigue aquí."));},900);return()=>window.clearTimeout(timer);},[details,loaded,token,recording]);
  const questions=familyInterviewQuestionGroups(name)[0].questions;
  const config=[{field:"interest_tags",options:interviewInterestOptions},{field:"social_play_tags",options:interviewSocialPlayOptions},{field:"home_activity_tags",options:interviewHomeActivityOptions},{field:"language_tags",options:interviewLanguageOptions},{field:"community_tags",options:interviewCommunityOptions},{field:"participation_support_tags",options:interviewParticipationSupportOptions}][step];
  const key=questions[step].key as keyof FamilyInterviewDetails;
  function dictation(){const Ctor=(window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition}).SpeechRecognition??(window as unknown as {webkitSpeechRecognition?:new()=>Recognition}).webkitSpeechRecognition;if(!Ctor){setMessage("El dictado no está disponible en este navegador. Puedes escribir tu respuesta o usar el micrófono del teclado.");return;}const r=new Ctor();recognition.current=r;r.lang="es-PE";r.continuous=false;r.interimResults=false;r.onresult=e=>setDetails(d=>({...d,[key]:[d[key],e.results[0][0].transcript].filter(Boolean).join(" ").slice(0,300),structured_options_version:2}));r.onerror=()=>setMessage("No pude escuchar. Puedes escribir o volver a intentar.");r.onend=()=>setRecording(false);setRecording(true);r.start();}
  return <main className="min-h-screen bg-[#edf5fa] px-4 py-8 text-[#172b52]"><div className="mx-auto max-w-3xl space-y-5"><header className="flex items-center gap-4"><AyniMascot/><div><h1 className="text-2xl font-bold">La familia nos cuenta</h1><p className="mt-2 text-sm">Responde solo lo que quieras compartir. La profesora revisará tus respuestas.</p></div></header>{loaded?<><p className="text-sm font-semibold">Pregunta {step+1} de {questions.length} · {name}</p><progress max={questions.length} value={step+1} className="h-2 w-full accent-[#087d96]"/><section className="space-y-5 rounded-2xl bg-white p-5 sm:p-8"><h2 className="text-xl font-bold">{questions[step].label}</h2><p className="text-sm text-[#526b87]">Puedes elegir varias opciones, escribir o dejar esta pregunta sin responder.</p><div className="flex flex-wrap gap-2">{config.options.map(o=>{const tags=((details as Record<string,unknown>)[config.field]??[]) as string[];return <button key={o.id} aria-pressed={tags.includes(o.id)} className={`min-h-11 rounded-xl border px-3 text-sm ${tags.includes(o.id)?"border-[#087d96] bg-[#e4f7f9]":"bg-white"}`} onClick={()=>setDetails(d=>({...d,[config.field]:tags.includes(o.id)?tags.filter(id=>id!==o.id):[...tags,o.id],structured_options_version:2}))}>{o.label}</button>;})}</div><label className="block text-sm font-semibold">Tu respuesta (opcional)<textarea className="mt-2 min-h-32 w-full rounded-xl border p-3 text-base font-normal" maxLength={300} value={String(details[key]??"")} onChange={e=>setDetails(d=>({...d,[key]:e.target.value,structured_options_version:2}))}/></label><Button variant="outline" onClick={()=>recording?recognition.current?.stop():dictation()}>{recording?"Detener dictado":"Dictar"}</Button></section><div className="flex flex-wrap justify-between gap-3"><Button variant="outline" disabled={!step||recording} onClick={()=>setStep(v=>v-1)}>Anterior</Button>{step<questions.length-1?<Button disabled={recording} onClick={()=>setStep(v=>v+1)}>Siguiente →</Button>:<Button disabled={recording} onClick={()=>void api("PUT",{details}).then(()=>setMessage("Gracias. Tus respuestas quedaron guardadas para la profesora."),e=>setMessage(e.message))}>Guardar respuestas</Button>}</div><Button variant="ghost" disabled={recording} onClick={()=>void api("PUT",{details}).then(()=>setMessage("Avance guardado. Puedes volver con este mismo enlace."),e=>setMessage(e.message))}>Guardar y continuar después</Button></>:!message?<p>Cargando entrevista…</p>:null}<p role="status" className="text-sm">{message}</p></div></main>;
}
