create table if not exists curriculum_source_documents (
  id uuid primary key, title text not null, source_url text not null unique, content_hash text not null,
  review_status text not null check (review_status in ('pending','verified','rejected')),
  retrieved_at timestamptz not null default now()
);
create table if not exists cycles (id uuid primary key, level_id uuid not null references levels(id), code text not null, official_text text, unique(level_id, code));
create table if not exists transversal_approaches (id uuid primary key, version_id uuid not null references curriculum_versions(id), code text not null, official_text text not null, unique(version_id, code));
alter table curriculum_versions add column if not exists source_document_id uuid references curriculum_source_documents(id);
alter table competencies add column if not exists source_document_id uuid references curriculum_source_documents(id), add column if not exists printed_page integer, add column if not exists pdf_page integer, add column if not exists section text, add column if not exists official_order integer, add column if not exists review_status text not null default 'pending' check (review_status in ('pending','verified','rejected')), add column if not exists reviewed_at timestamptz, add column if not exists content_hash text;
alter table performances add column if not exists source_document_id uuid references curriculum_source_documents(id), add column if not exists printed_page integer, add column if not exists pdf_page integer, add column if not exists section text, add column if not exists official_order integer, add column if not exists review_status text not null default 'pending' check (review_status in ('pending','verified','rejected')), add column if not exists reviewed_at timestamptz, add column if not exists content_hash text;
create table if not exists capacities (id uuid primary key, competency_id uuid not null references competencies(id), official_text text not null, source_document_id uuid references curriculum_source_documents(id), printed_page integer, pdf_page integer, section text, official_order integer, review_status text not null default 'pending' check (review_status in ('pending','verified','rejected')), reviewed_at timestamptz, content_hash text);
create table if not exists standards (id uuid primary key, competency_id uuid not null references competencies(id), cycle_id uuid references cycles(id), official_text text not null, source_document_id uuid references curriculum_source_documents(id), printed_page integer, pdf_page integer, section text, official_order integer, review_status text not null default 'pending' check (review_status in ('pending','verified','rejected')), reviewed_at timestamptz, content_hash text);
